dist: xenial
sudo: required
language: node_js
node_js:
  - "9.4.0"
  
branches:
  only:
  - master
  - disputeVoting
matrix:
  include:
    - os: linux
      dist: xenial
      before_install:
      - sudo add-apt-repository ppa:ethereum/ethereum -y
      - sudo apt-get update
      - sudo apt-get install build-essential -y
      - sudo apt-get install gcc g++ libssl-dev libudev-dev pkg-config
      - curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - rm -rf node_modules

install:
  - cd ./src
  - npm install
  - npm install -g ganache-cli truffle

script:
  - testrpc-sc --gasLimit 0xfffffffffff --gasPrice 0x01 --network-id 777 -p 8545 > /dev/null &
  - sleep 5 
  - npm test
after_script:
  - npm run coverage && cat coverage/lcov.info | coveralls